### ISSUE TITLE
Perspectives Flipped

### ISSUE THREAD

**Issue by GEMISIS** [googlesamples/cardboard-java#10]
I'm not sure if this was intentional, but it looks as though the eyes are flipped around.  The views for each one seem to be off, and when using the application, I have to go cross-eyed to view it properly.  While this may be a problem with the IPD as well, I'm noticing that the right eye sees more on the left side then the left eye (in a personal app, and the normal Cardboard demo app on the Play Store).

**Comment by nathanmartz** [comment]
Closing very old thread.
