### ISSUE TITLE
rendering with renderscript on CPU?

### ISSUE THREAD

**Issue by flankechen** [googlesamples/cardboard-java#14]
I have run this with nexus 5, lenovo K910, oppo find5 all showing up logs like:

10-28 16:14:55.042: I/MainActivity(9162): onSurfaceCreated
10-28 16:14:55.052: W/CardboardView(9162): Surface size 1920x1005 does not match the expected screen size 1920x1080. Rendering is disabled.
10-28 16:14:55.052: I/MainActivity(9162): onSurfaceChanged
10-28 16:14:55.052: I/MainActivity(9162): surfaceWidht960
10-28 16:14:55.052: I/MainActivity(9162): surfaceHeight1005
10-28 16:14:55.112: V/RenderScript(9162): Application requested CPU execution
10-28 16:14:55.112: V/RenderScript(9162): 0x7733da88 Launching thread(s), CPUs 4
10-28 16:14:55.132: E/ffi_jank(9162): timespan = 64.74047
10-28 16:14:55.182: E/ffi_jank(9162): timespan = 32.909218
10-28 16:14:55.212: I/MainActivity(9162): onSurfaceChanged
10-28 16:14:55.212: I/MainActivity(9162): surfaceWidht960
10-28 16:14:55.212: I/MainActivity(9162): surfaceHeight1080

surface size and the screen size is never matched. And is this means the whole thing is rendered in CPU with renderscript?

Any idea about this?

**Comment by zbendefy** [comment]
I suppose there is a total of 75 pixel tall padding/gap in the layout, which you need to remove.

**Comment by flankechen** [comment]
zbendefy, thanks for your replay.
I have try fullscreen mode, phones with or without navigate bar. It seems that this is bug of cardboard SDK, some phones even render views "super small", which is even in the latest update and some of the carboard games.
Hopefully, google guys would fixed this soon.

**Comment by nathanmartz** [comment]
Closing old and likely fixed thread. Please reopen if issue is still relevant.
