### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by 1537592846** [googlesamples/cardboard-java#16]
The Studio asks me to sync the Gradle project, but fails every time. Here is the error.

Error:FAILURE: Build failed with an exception.

* What went wrong:
Task '' not found in root project 'cardboard-master'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

I copied the treasure hunto project to understand it better, but I can't even run simulation on it.

**Comment by nathanmartz** [comment]
Bug is long fixed. Closing.
