### ISSUE TITLE
Correct headtracking jitter with slerp.

### ISSUE THREAD

**Issue by dcerisano** [googlesamples/cardboard-java#17]
Headtracking directly from the sensor quaternion is too sensitive (jitter - but still not as bad as Unity!).
Using spherical linear interpolation significantly improves the subjective experience of headtracking. Pretty sure Oculus does this.

I have corrected the problem with an older github cardboard sdk source project, 
https://github.com/Zomega/Cardboard
by using quaternions and  spherical linear interpolation (slerp).

Default headtracking currently returns a rotational matrix directly from sensors.

Could this please be incorporated into the headtracker class?

**Comment by keyboardsurfer** [comment]
If this is a potential fix to this sample please prepare a pull request.

**Comment by D3m0n92** [comment]
Nice! Good work @dcerisano !

**Comment by dcerisano** [comment]
I will prepare a pull request the moment Google releases the cardboard sdk as open source.
There is nothing to submit the pull request against currently.

**Comment by nathanmartz** [comment]
Thanks for the note. Is there an actual fix here? The linked repo is just a clone of a decompiled SDK as far as I can tell.

**Comment by dcerisano** [comment]
+nathanmartz, since the head tracking class is not open source, it cannot be fixed on github.
