### ISSUE TITLE
HeadTransform.getForwardVector question

### ISSUE THREAD

**Issue by zbendefy** [googlesamples/cardboard-java#18]
I'm trying to use the HeadTransform.getForwardVector() method to get the camera view direction, but the returned value seems to be off. When i rotate my phone on the screen's plane (roll) in a full circle, the z value (3rd item in the returned array) is changing from -1 to 1, and back to -1, even though the camera direction stays the same (i'm looking at the same object during rotating).

The vector itself matches the actual viewing direction at some yaws, but at others it does not, and is completely off.

phone type: galaxy note 3

**Comment by devinweidinger** [comment]
You can just use transform.forward on the camera's transform. Or preferably
on a game object that is right in between the two cameras.

On Mon, Jan 5, 2015 at 11:34 AM, zbendefy <notifications@github.com> wrote:

> I'm trying to use the HeadTransform.getForwardVector() method to get the
> camera view direction, but the returned value seems to be off. When i
> rotate my phone on the screen's plane (roll) in a full circle, the z value
> (3rd item in the returned array) is changing from -1 to 1, and back to -1,
> even though the camera direction stays the same (i'm looking at the same
> object during rotating).
>
> phone type: galaxy note 3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlesamples/cardboard-java/issues/18>.
>



-- 
*DEVIN S WEIDIGNER*
*BA in Game Art & Design*
*254.458.4393*

**Comment by zbendefy** [comment]
Is that in the cardboard api? I can't seem to find it.

Also what does the HeadTransform.getForwardVector() give me exactly?

**Comment by nathanmartz** [comment]
FYI that we think this is an actual SDK bug. Looking into a fix for next release.
