### ISSUE TITLE
eye.getEyeView() and eye.getEyePerspective() return NaN matrices

### ISSUE THREAD

**Issue by zbendefy** [googlesamples/cardboard-java#20]
Hello! In my app, at first launch, everything seems to be fine. After getting back to the main menu, and starting a new game (with every object recreated, every static field reinitialized), only 2D objects are rendered. I looked into it, and it seems that in the onDrawEye method, the given view and perspective matrices are NaN. Is there something i forgot to reset, or is this a bug in the api?

EDIT: It was my mistake. I forgot to call super.onPause() in my CardboardView extending class...

**Comment by rsanchezsaez** [comment]
This may be due to the `HeadTracker` matrix degenerating under some some circumstances. As a workaround, I'd try pausing and resuming the `CardboardView` on game restart. Like this:

         getCardboardView().onPause();
         getCardboardView().onResume();

which resets the `HeadTracker` as a side effect.

**Comment by zbendefy** [comment]
Thanks for your reply, it doesn't seem to fix it though :(
The HeadTransform instance i get in the onNewFrame() method is also NaN, and the eye matrices stem from that matrix. I recreate the activity on every new game launch (and also the CardboardView with it), so it's strage...maybe some system resources are not released properly? or is there a static field that should be resetted inside the api?

Any tips for any other workarounds?

**Comment by rsanchezsaez** [comment]
You can close the issue if you want.
