### ISSUE TITLE
Issues with 0.5.4 and Note 3

### ISSUE THREAD

**Issue by svenhenrik** [googlesamples/cardboard-java#23]
Hi, this is a rather bad bug report I'm afraid, but as no one else has reported it I figured it's better than nothing. 

I recently upgraded my app VRTV (https://play.google.com/store/apps/details?id=se.chai.vrtv.free) to 0.5.4 and got a report from a user that it stopped working on his Galaxy Note 3. It did not detect head movement at all. I don't have one to test on myself unfortunately, but after browsing the Play Store and reading reviews for other apps that had moved to 0.5.4, including the official Cardboard App, I decided to downgrade back to 0.5.3. Lots of one star reviews stating that things stopped working. 

I imagine Note 3 is a pretty common device among Cardboard users, so I assume Google has tested the SDK before releasing? My app doesn't use the SDK in any strange way that I'm aware of, it's based on the sample and pretty much just throws a different set of triangles on the screen.

**Comment by nathanmartz** [comment]
We test extensively on that device. Please try updating to 0.6.0. Reopen the thread if you still have issues.
