### ISSUE TITLE
Demo Scene sample not working in LG 

### ISSUE THREAD

**Issue by Angie-Ie** [googlesamples/cardboard-java#25]
When try demo scene from cardboard (unity 5.1)  in LG L90 , the application always force close. But when i tried running google cardboard demo in play store ( https://play.google.com/store/apps/details?id=com.google.samples.apps.cardboarddemo&hl=en) nothing problem show. 
any solution?

**Comment by smdol** [comment]
Can you run "adb logcat" and see if there are any error messages that indicate where the crash is coming from?

**Comment by Angie-Ie** [comment]
Yes I have runned the adb logcat. In the script cardboard.cs, this part: InitDevice(); crashed and went error, it force close the program. But when I tried the demo scene of cardboard package on other smartphone (Xiaomi HM1S) it successfully worked.
FYI:
- The android version of LG L90 is Kitkat 4.4.
- The Windy Day from cardboard demo successfully worked too.

**Comment by smdol** [comment]
Can you paste the adb logcat messages from Unity here?  You can use "adb logcat -s Unity" so all the log messages from other Android services are not included.

**Comment by Angie-Ie** [comment]
C:\Users\Vina\AppData\Local\Android\sdk\platform-tools> adb logcat -s Unity
--------- beginning of /dev/log/system
--------- beginning of /dev/log/main
D/Unity   (11709): GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_A
MD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_fra
mebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_
10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_textur
e GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_element_index
_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program
_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rg
ba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_te
xture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_ver
tex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_
alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global
_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM
_writeonly_rendering GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_d
ec
D/Unity   (11709): ode GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_ren
der_to_texture GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_d
isjoint_timer_query
I/Unity   (11709): CardboardMain (Cardboard)
I/Unity   (11709):
I/Unity   (11709): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (11709):
I/Unity   (11709): Profile
I/Unity   (11709):
I/Unity   (11709): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (11709):
I/Unity   (11709): AndroidVRDevice
I/Unity   (11709):
I/Unity   (11709): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (11709):
I/Unity   (11709): 236.6095
I/Unity   (11709):
I/Unity   (11709): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (11709):
I/Unity   (11709): SetEventCallback
I/Unity   (11709):
I/Unity   (11709): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (11709):

**Comment by smdol** [comment]
Hm.  I don't really see any useful messages in that listing.  I would next suggest running adb logcat (without -s Unity), and look for the long message from Unity ("D/Unity (???): GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_A
MD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_fra
mebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888..."), which is where the app is starting.  Then scan after that point to where the crash occurs.

Is there a stack trace in the log?  It would be helpful to see the exact point where the crash happens.

**Comment by Angie-Ie** [comment]
Hai, i did try, the scan after that point not show any errors
D/Unity(23684): GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor
GL_AMD_program_binary_Z400 GL_EXT_debug_label
                GL_EXT_debug_marker GL_EXT_discard_framebuffer
GL_EXT_robustness GL_EXT_texture_format_BGRA8888
                GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence
GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture
                GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_image_external
GL_OES_element_index_uint GL_OES_fbo_render_mipmap
                GL_OES_fragment_precision_high GL_OES_get_program_binary
GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map
                GL_OES_rgb8_rgba8 GL_OES_standard_derivatives
GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float
                GL_OES_texture_half_float_linear GL_OES_texture_npot
GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2
                GL_OES_vertex_array_object GL_QCOM_alpha_test
GL_QCOM_binning_control GL_QCOM_driver_control
                GL_QCOM_perfmon_global_mode GL_QCOM_extended_get
GL_QCOM_extended_get2
                GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering
GL_EXT_sRGB GL_EXT_sRGB_write_control
                GL_EXT_texture_sRGB_dec
07-13 10:14:27.562: D/Unity(23684): ode GL_EXT_texture_filter_anisotropic
                GL_EXT_multisampled_render_to_texture
GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float
                GL_EXT_disjoint_timer_query

07-13 10:14:27.572: D/BluetoothAdapter(1871): 1106597072: getState() :
 mService = null. Returning STATE_OFF

07-13 10:14:27.582: D/BluetoothAdapter(1871): 1106597072: getState() :
 mService = null. Returning STATE_OFF

07-13 10:14:27.582: D/BluetoothAdapter(1871): 1106597072: getState() :
 mService = null. Returning STATE_OFF

07-13 10:14:27.582: D/BluetoothAdapter(1235): 1106803368: getState() :
 mService = null. Returning STATE_OFF

07-13 10:14:27.592: D/BluetoothAdapter(1871): 1106597072: getState() :
 mService = null. Returning STATE_OFF

07-13 10:14:27.602: D/BluetoothAdapter(1871): 1106597072: getState() :
 mService = null. Returning STATE_OFF

07-13 10:14:27.602: D/BluetoothAdapter(1871): 1106597072: getState() :
 mService = null. Returning STATE_OFF

07-13 10:14:27.602: D/BluetoothAdapter(1871): 1106597072: getState() :
 mService = null. Returning STATE_OFF

07-13 10:14:27.612: I/RemoteControlStatusBar(1235): showRemoteControlView
[isEnabled]:false [isPortraitOri]:false

07-13 10:14:27.612: I/RemoteControlStatusBar(1235): showRemoteControlView
[irRcVisibility]:8 [irRcInfoVisibility]:8

07-13 10:14:27.612: I/RemoteControlStatusBar(1235): End
showRemoteControlView

Using cardboard v  0.4.10 running well in my phone
Thank you for your help

**Comment by nathanmartz** [comment]
Closing old thread. Please reopen if there are still issues w/ latest SDK.
