### ISSUE TITLE
Feature request: Disable head tracking

### ISSUE THREAD

**Issue by svenhenrik** [googlesamples/cardboard-java#27]
A lot of my users are experiencing problems with head tracking in later SDK:s, the big shift being between version 0.5.3 and 0.5.4. 

I would like to experiment with providing my own head tracking, but the SDK doesn't make it very easy. I currently just ignore the headtransform and provide my own, but it's still being calculated in the background, wasting precious cycles.

Any chance we could get a call to disable head tracking completely? Or better yet, allow us to hook our own HeadTracker implementation into the SDK.

**Comment by TheFakeMontyOnTheRun** [comment]
That could be useful.

@svenhenrik , for now, I suggest you counter the rotations from eye matrix. I did that for when my user decides to disable the VR mode, allowing for joystick control of the XZ angle (but I decided to keep the YZ rotation).

Not the best and optimal solution, but works.

**Comment by svenhenrik** [comment]
Yeah, that's how I do it now, sort of. I invert the headmatrix and apply it to the eyeview in the first calls to onDrawEye and save the two eye matrices, then I apply them onto my own rotation. Works, but the SDK is still wasting resources doing headtracking in the background.

**Comment by nathanmartz** [comment]
Thanks for the feedback but our goal is to improve head tracking, not disable it.
