### ISSUE TITLE
Screen cannot unlock after falling asleep with Cardboard open

### ISSUE THREAD

**Issue by appsforartists** [googlesamples/cardboard-java#3]
If I run the Cardboard app on the L Developer Preview and my phone falls asleep, I am not able to interact with my lock screen via touch.  Holding the power button down until I get the "Power Off?" dialog re-enables the touchscreen.

**Comment by keyboardsurfer** [comment]
L developer preview has been some time ago.
There were no more people adding to this issue.
Feel free to re-open if the issue still occurs.
