### ISSUE TITLE
0.5.7 and 0.5.8

### ISSUE THREAD

**Issue by mjsibbald** [googlesamples/cardboard-java#31]
Sinds these last 2 version, I'm getting black screen and no error. Everything as fine in 0.5.6.

showing video and images. Anybody running into this?

Thanks

**Comment by mjsibbald** [comment]
Just found out when I set setLowLatencyModeEnabled(false) it shows again. Why is this blocking in these versions?

**Comment by Gousetis** [comment]
Can you confirm that your render callback is being executed? If you don't have logs/print statements coming from your render loop, it is likely that the time synchronization logic has a bug in it.

If you are getting draw calls, can you check for GL errors, and let me know which Android API version you are running on? Low-latency mode has various implementations based on API, and the bug will depend on what version your phone is running.

**Comment by nathanmartz** [comment]
Closing thread due to lack of response from OP.
