### ISSUE TITLE
Black belt on the bottom of the screen

### ISSUE THREAD

**Issue by jtuta** [googlesamples/cardboard-java#35]
Hello,

There seems to be Android bug regarding immersive mode that can be replicated also in this app. Please  see bug report on android tracker: https://code.google.com/p/android/issues/detail?id=170752

In the comment 4 I describe bug inside cardboard-java.

**Comment by dav-cz** [comment]
Looks like this has been fixed with Android 6.0.1. Please re-open if you see this issue again.
