### ISSUE TITLE
switching off vrmode renders the scene twice

### ISSUE THREAD

**Issue by fcoulombe** [googlesamples/cardboard-java#36]
putting a breakpoint on onDrawEye(Eye eye) will trigger twice per frame.

It sounds a bit redundant since I think it'll just draw on top of the previous frame.

**Comment by jdduke** [comment]
Yeah, this looks like an issue with the SDK, and an internal bug has been filed for tracking. For completeness, which version of the SDK are you using?

**Comment by fcoulombe** [comment]
latest

**Comment by jdduke** [comment]
This should be fixed in the next release, thanks for the bug report. I'll keep this issue open until the fix ships.

**Comment by dav-cz** [comment]
This should be now fixed with 0.6. Thanks for the report!
