### ISSUE TITLE
Big parallax with left and right eyes

### ISSUE THREAD

**Issue by guanshan** [googlesamples/cardboard-java#44]
When I use cardboard on a device which has a big screen, 5.5 inch.
And it's resolution is  2560*1440，dpi=640.
The question is that the parallax is too big, so that I can see two non overlapping images through a VR  device.
So, what should I to to fix it?

Thanks.

**Comment by openforeveryone** [comment]
This should be corrected by pressing the settings button, pressing "setup" then "switch viewer". You can then scan the QR code printed on your cardboard device.
If there is no QR code for your cardboard or it does not work, you can make a new one at https://www.google.co.uk/get/cardboard/viewerprofilegenerator/. (This may not work with Firefox)

**Comment by dav-cz** [comment]
Hi Guanshan. It looks like your phone might be reporting an incorrect DPI, which prevents the SDK from drawing the two images at the right place on the screen.
According to the numbers you gave, the phone DPI should be around 534, not 640.

What is your phone model? Even better, could you give us the output of the following: 
adb shell getprop | grep "model\|manufacturer\|hardware\|product.name\|lcd_density"

This way we could add a DPI override in our SDK for your phone model.
Thanks!

**Comment by guanshan** [comment]
@dav-cz Thanks for your reply.
It's our own VR machine.
I change the dpi, and it works finally.
Thank you so much!

**Comment by dav-cz** [comment]
Great, glad it worked!  I will close this issue then.
