### ISSUE TITLE
Expose primary button type in CardboardDeviceParams

### ISSUE THREAD

**Issue by cemrich** [googlesamples/cardboard-java#49]
You can generate a cardboard device profile at https://www.google.com/intl/de_ALL/get/cardboard/viewerprofilegenerator/, specifying the "Primary button type" as `none`, `magnet`, `touch` or `indirect touch`. `CardboardDeviceParams#getHasMagnet()` provides a way to differentiate between a magnet trigger or any other input method. There is however no way to distinguish between cardboard devices with no trigger, with touch trigger or with indirect touch trigger.

This function could be useful to provide different user interfaces for different device capabilities.

**Comment by nathanmartz** [comment]
This is by design so that we don't fragment the user experience.

**Comment by cemrich** [comment]
Thank you for your response!

Just to understand your design decision: Why is it you can distinguish between the magnet trigger and any other or no input method then? Is this a leftover from an older API? 

Please don't get me wrong, but I think a good UI for devices without trigger has to look different than for devices with any trigger (regardless of the type). For example you would need a "select by long gaze" feature for devices without trigger only. For other devices the progress indicator could be confusing, because you can select items more intuitively by using the provided button. So `CardboardDeviceParams#getHasTrigger()` instead of `CardboardDeviceParams#getHasMagnet()` would help a lot.

**Comment by nathanmartz** [comment]
The Cardboard SDK implements the official WWGC spec, which requires the viewer provide a single button input. The getHasMagnet function is leftover and may be removed in a future version of the SDK.

**Comment by cemrich** [comment]
Thank you very much for the clarification.
