### ISSUE TITLE
Functionality to allow running on Gear VR out of the box ?

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-java#50]
Is there any (legal) way Google could add a functionality that would allow Google Cardboard app(s) to run on Gear VR out of the box ?

I've heard that it's already possible, but involves some kind of package disabler app and some hackery. It's not consumer friendly way, so it seems that native solution would be a way to go.

**Comment by nathanmartz** [comment]
Sorry, but running on GearVR requires using their SDK, which only they distribute. If you would like them to support Cardboard apps, that would be a great request to submit to Samsung and/or Oculus.
