### ISSUE TITLE
Distortion enabled drops frames

### ISSUE THREAD

**Issue by mjsibbald** [googlesamples/cardboard-java#54]
I know this is a known issue, but the distortion is creating a lot of lag.
Is there anything or any tips to improve?

Thanks

**Comment by nathanmartz** [comment]
Which SDK are you using? This is somewhat better in 0.6.0.

Also, the fastest solution is to implement [Vertex Distortion](http://gamasutra.com/blogs/BrianKehrer/20160125/264161/VR_Distortion_Correction_using_Vertex_Displacement.php)
