### ISSUE TITLE
cardboard.jar download link is 404

### ISSUE THREAD

**Issue by xdreamz** [googlesamples/cardboard-java#62]
Help me! cardboard.jar download link is 404

https://github.com/googlesamples/cardboard-java/blob/master/CardboardSample/libs/cardboard.jar
and
https://github.com/googlesamples/cardboard-java/blob/master/CardboardSample/libs/libprotobuf-java-2.6-nano.jar

**Comment by mariobodemann** [comment]
afaik, there are no jar files any more. You would need to download the sdk sample and us the aar files in the libraries folder ... 

https://developers.google.com/cardboard/android/download

**Comment by dav-cz** [comment]
@mariobodemann is correct, no more jar files, we use aar files instead.

I'm going to close this bug. @xdreamz, let us know if you notice any broken links to the jar files in our documentation. Thanks!

**Comment by andrewminton** [comment]
Is there a best practice for importing these .aar files I nto our own projects? Classes aren't available when importing the .aar files alone and the docs aren't very clean on this change to .aar at all.

**Comment by dav-cz** [comment]
Andrew, did you look at https://developers.google.com/cardboard/android/get-started#start_your_own_project?

It explains how to use the aars into your own project either using Android Studio or directly editing your gradle file.
