### ISSUE TITLE
What time can user-defined video FullScreen UI？

### ISSUE THREAD

**Issue by guanpy** [googlesamples/cardboard-java#63]

**Comment by nathanmartz** [comment]
I'm sorry but I don't understand this question. Can you be more specific about your use case and the problem you are trying to solve?

**Comment by guanpy** [comment]
I want to custom players like this
![](https://github.com/guanpy/VRDroid/blob/master/screenshot/utovr.jpg)

**Comment by nathanmartz** [comment]
We don't plan to provide that exactly, but you can use the existing widgets and add your own UI on top of them if you like.
