### ISSUE TITLE
Google Cardboard Plastic stopped working after the first 3 uses

### ISSUE THREAD

**Issue by R1ck77** [googlesamples/cardboard-java#64]
Hi,

I'm not sure if this is the proper place, but since the "Google Cardboard Plastic" site is a bit lacking (not complaining, as at this stage they are doing great), I'll post here.

Started to use the Google Cardboard Plastic for about a day, and everything was astonishing: graphic, smoothness over the top, and no drifting, not even a little bit (eat dirt Oculus)!

After the third time I put it on, I started to see that the graphic quality was degrading, and artifact started to appear: everything looks a little blurred now, and... I know it sounds crazy, bute there are... fingerprint like distortions on the image?!? I'm quite puzzled.

I think I meet the hardware requirements (2 eyes, both 20/20. the CPU might be a little underpowered, but the specifics on the site aren't clear): I tried to put them on and off again, changed the language settings and started to speak German (in case it's a localization issue), but nothing worked.

Please let me know, or redirect me to the proper page! 

Also, if you are behind the project, congratulations for the **awesome work**!

PS: I really hope that a reboot wouldn't be necessary

**Comment by nathanmartz** [comment]
Thanks for the feedback, but we need to keep this focused on actual issues :)

**Comment by R1ck77** [comment]
fair enough :) 

Congratulations to whoever did that, anyway!
