### ISSUE TITLE
How to use the code directly into the VR MODE and FullScreen Mode？

### ISSUE THREAD

**Issue by babysource** [googlesamples/cardboard-java#66]

**Comment by dav-cz** [comment]
There's no official way to do this programmatically yet, but we could add one in future versions.

If you absolutely need this now, you can work around it by inspecting the view hierarchy to find the "cardboard" VR mode button, and programmatically call performClick() on it. No guarantee that this will be supported by future versions of the API, though.

**Comment by nihalmehdi** [comment]
Below code works for me...
View framelayout = ((ViewGroup) panoWidgetView).getChildAt(0);
        ((ViewGroup)((ViewGroup)((ViewGroup)framelayout).getChildAt(1)).getChildAt(2)).getChildAt(0).performClick();

**Comment by hegazy** [comment]
I think this is a very important feature. Videos to be opened in fullscreen is a necessity, I think.

**Comment by fjrobles** [comment]
nihalmehdi, where do you put the code?? in class VideoLoaderTask?

**Comment by nihalmehdi** [comment]
I put the code within 
 protected void onCreate(Bundle savedInstanceState) {
....

View framelayout = ((ViewGroup) panoWidgetView).getChildAt(0);
((ViewGroup)((ViewGroup)((ViewGroup)framelayout).getChildAt(1)).getChildAt(2)).getChildAt(0).performClick();
...
}

**Comment by fjrobles** [comment]
Tnx so much!!!! but the app doesn´t runs. I attach two screenshoots!!!

![captura de pantalla 2016-07-28 a las 18 15 08](https://cloud.githubusercontent.com/assets/11178730/17218044/bea5a262-54e6-11e6-8627-54b96673cbcb.png)

![captura de pantalla 2016-07-28 a las 18 17 34](https://cloud.githubusercontent.com/assets/11178730/17218143/142da8e2-54e7-11e6-8dec-d770143a234e.png)

**Comment by Tanksta** [comment]
If it is still needed. Make sure you have the lastest version ( tested on 0.9.1 )
 For fullscreen use
videoWidgetView.setDisplayMode(VrVideoView.DisplayMode.FULLSCREEN_MONO);

for vr glasses use
videoWidgetView.setDisplayMode(
        VrVideoView.DisplayMode.FULLSCREEN_STEREO
    );
