### ISSUE TITLE
Redundant READ_EXTERNAL_STORAGE in "Getting Started" documentation

### ISSUE THREAD

**Issue by R1ck77** [googlesamples/cardboard-java#68]
Not a bug, but a style issue: the `READ_EXTERNAL_STORAGE` permission in the Treasure Hunt guide is redundant and should be removed, as the documentation clearly states that:

> Any app that declares the WRITE_EXTERNAL_STORAGE permission is implicitly granted this permission.

[http://developer.android.com/reference/android/Manifest.permission.html#READ_EXTERNAL_STORAGE](`READ_EXTERNAL_STORAGE` on the Manifest.permissions page)

The same extra permission is declared in the "treasurehunt" `AndroidManifest.xml` as well.

**Comment by nathanmartz** [comment]
Thank you for the bug report!
