### ISSUE TITLE
Top-Bottom stereoscopic video not interpreted correctly

### ISSUE THREAD

**Issue by leoncvlt** [googlesamples/cardboard-java#85]
The documentation says: 
> Stereo videos should be 1:1 aspect ratio.

I tried the simplevideoexample with a custom stereoscopic video of mine, 1080x1080 .mp4 encoded with h264. The video plays fine on Oculus Rift and GearVr. In the app, however, is not interpreted correctly as it's played fully in both eyes (as in, the top bottom separation is visible in the video).

I tried looking at the provided example video file (congo.mp4) and it's quite a strange format. Adobe Premiere says it's a 1920*1080 video file with a pixel aspect ratio of 0.565.

I tried and encoded it with that aspect ratio with ffmpeg, but still no luck.

How can I get my top-bottom stereoscopic video to play correctly?

**Comment by leoncvlt** [comment]
Developing on a Samsung Galaxy S5 with Android 4.4.2

**Comment by nathanmartz** [comment]
Hi, Leonardo. Sorry for the confusion. The current version requires you
include the YT 360 metadata (
https://support.google.com/youtube/answer/6178631?hl=en) for stereo. We'll
change the API in a future release to let you specify whether the content
is mono or stereo, but for now this will work for you.

-Nathan

**Comment by leoncvlt** [comment]
I see, worth mentioning in the supported format sections maybe.

Used the python script and now works fine. Thanks!
